CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id BIGINT UNIQUE,
    username TEXT,
    first_name TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    last_name TEXT
);

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.withings_tokens (
    telegram_id BIGINT PRIMARY KEY,
    access_token TEXT,
    refresh_token TEXT,
    updated_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ
);

ALTER TABLE public.withings_tokens DISABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.workouts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id BIGINT,
    exercise TEXT,
    sets INTEGER,
    reps INTEGER,
    weight_lbs NUMERIC,
    logged_at TIMESTAMPTZ DEFAULT now(),
    notes TEXT
);

ALTER TABLE public.workouts
    ADD COLUMN IF NOT EXISTS weight_lbs NUMERIC,
    ADD COLUMN IF NOT EXISTS logged_at TIMESTAMPTZ DEFAULT now(),
    ADD COLUMN IF NOT EXISTS notes TEXT;

CREATE INDEX IF NOT EXISTS idx_workouts_user_logged_at ON public.workouts(user_id, logged_at DESC);
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.body_metrics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id BIGINT,
    weight_lbs NUMERIC,
    body_fat_pct NUMERIC,
    muscle_mass_lbs NUMERIC,
    recorded_at TIMESTAMPTZ DEFAULT now(),
    snapshot_date DATE DEFAULT CURRENT_DATE
);

ALTER TABLE public.body_metrics
    ADD COLUMN IF NOT EXISTS weight_lbs NUMERIC,
    ADD COLUMN IF NOT EXISTS body_fat_pct NUMERIC,
    ADD COLUMN IF NOT EXISTS muscle_mass_lbs NUMERIC,
    ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ DEFAULT now(),
    ADD COLUMN IF NOT EXISTS snapshot_date DATE DEFAULT CURRENT_DATE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_body_metrics_user_snapshot_date ON public.body_metrics(user_id, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_body_metrics_user_recorded_at ON public.body_metrics(user_id, recorded_at DESC);
ALTER TABLE public.body_metrics ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.whoop_snapshots (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id BIGINT,
    recovery_score NUMERIC,
    hrv NUMERIC,
    resting_hr NUMERIC,
    sleep_duration_hrs NUMERIC,
    sleep_efficiency_pct NUMERIC,
    sleep_performance_pct NUMERIC,
    strain NUMERIC,
    spo2 NUMERIC,
    respiratory_rate NUMERIC,
    skin_temp NUMERIC,
    recorded_at TIMESTAMPTZ DEFAULT now(),
    snapshot_date DATE DEFAULT CURRENT_DATE
);

ALTER TABLE public.whoop_snapshots
    ADD COLUMN IF NOT EXISTS recovery_score NUMERIC,
    ADD COLUMN IF NOT EXISTS hrv NUMERIC,
    ADD COLUMN IF NOT EXISTS resting_hr NUMERIC,
    ADD COLUMN IF NOT EXISTS sleep_duration_hrs NUMERIC,
    ADD COLUMN IF NOT EXISTS sleep_efficiency_pct NUMERIC,
    ADD COLUMN IF NOT EXISTS sleep_performance_pct NUMERIC,
    ADD COLUMN IF NOT EXISTS strain NUMERIC,
    ADD COLUMN IF NOT EXISTS spo2 NUMERIC,
    ADD COLUMN IF NOT EXISTS respiratory_rate NUMERIC,
    ADD COLUMN IF NOT EXISTS skin_temp NUMERIC,
    ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ DEFAULT now(),
    ADD COLUMN IF NOT EXISTS snapshot_date DATE DEFAULT CURRENT_DATE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_whoop_snapshots_user_snapshot_date ON public.whoop_snapshots(user_id, snapshot_date);
CREATE INDEX IF NOT EXISTS idx_whoop_snapshots_user_recorded_at ON public.whoop_snapshots(user_id, recorded_at DESC);
ALTER TABLE public.whoop_snapshots ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.chat_history (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id BIGINT,
    role TEXT CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_chat_history_user_created_at ON public.chat_history(user_id, created_at DESC);
ALTER TABLE public.chat_history ENABLE ROW LEVEL SECURITY;
